/*
 * Auto-generated by Frida. Please modify to match the signature of SSL_write.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    // args[1] is the buffer
    // args[2] is the length
    const buf = args[1];
    const len = args[2].toInt32();

    if (len > 0) {
      log(\n[+] SSL_write captured (${len} bytes):);
      
      // FIX: Use hexdump() to convert memory to a string, 
      // and console.log() to print it safely.
      console.log(hexdump(buf, {
        offset: 0,
        length: len,
        header: true,
        ansi: true
      }));
    }
  },

  onLeave(log, retval, state) {
  }
});